import Foundation

struct CommandItem: Codable, Equatable {
    var id: String
    var title: String
    var bind: String
    var command: String
    var aliases: [String]
    var icon: String
    var rank: Double
}

enum Paths {
    static let home = FileManager.default.homeDirectoryForCurrentUser
    static let dir = home.appendingPathComponent(".config/CommandK")
    static let commands = dir.appendingPathComponent("commands.json")
    static let skhdrc = home.appendingPathComponent(".skhdrc")
    static let launcher = dir.appendingPathComponent("command-k")
}

enum Config {
    static func load() -> [CommandItem] {
        let urls = [Paths.commands, bundledCommands()].compactMap { $0 }
        for url in urls {
            if let data = try? Data(contentsOf: url),
               let items = try? JSONDecoder().decode([CommandItem].self, from: data) {
                return items
            }
        }
        return []
    }

    static func save(_ items: [CommandItem]) throws {
        try FileManager.default.createDirectory(at: Paths.dir, withIntermediateDirectories: true)
        let data = try JSONEncoder.pretty.encode(items)
        try data.write(to: Paths.commands, options: .atomic)
    }

    static func writeSkhdrc(_ items: [CommandItem]) throws {
        var lines: [String] = [
            "# Generated by CommandK. Change shortcuts in CommandK Settings.",
            "",
            "cmd - k [",
            "    \"Superhuman\" ~",
            "    \"Linear\" ~",
            "    \"CommandK\" ~",
            "    * : \(Paths.launcher.path)",
            "]",
            ""
        ]
        for item in items where !item.bind.isEmpty {
            lines.append("\(item.bind) : \(item.command)")
        }
        lines.append("")
        try lines.joined(separator: "\n").write(to: Paths.skhdrc, atomically: true, encoding: .utf8)
    }

    static func reloadSkhd() {
        let task = Process()
        task.executableURL = URL(fileURLWithPath: "/opt/homebrew/bin/skhd")
        task.arguments = ["--reload"]
        try? task.run()
    }

    static func bundledCommands() -> URL? {
        let src = URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent()
            .deletingLastPathComponent()
            .appendingPathComponent("Resources/commands.json")
        return FileManager.default.fileExists(atPath: src.path) ? src : nil
    }
}

private extension JSONEncoder {
    static var pretty: JSONEncoder {
        let e = JSONEncoder()
        e.outputFormatting = [.prettyPrinted, .sortedKeys]
        return e
    }
}
